### PR TITLE
Order Notes: Add `author` to notes, and `added_by_user` flag to note creation

### LINKED ISSUE #40: Orders: Add `author` to notes list response
Currently in wp-admin, the notes list display shows the user who left the comment:

screen shot 2017-08-11 at 1 21 39 pm

This has also been carried into the display for order notes in calypso:

screen shot 2017-08-11 at 1 22 26 pm

So we need to get this info from the API (and presumably also send it when creating a note as well).

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #40 

This PR adds an `author` to note responses, listing either `system` or the user display name of the user who created the note. This also adds a different flag, `added_by_user`, to the create call, which if true will set the note author to the currently-logged-in user (the user who authenticated the API request). `added_by_user` was chosen to match the [function `add_order_note`](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Order.html#1430-1474).

This also adds tests for listing notes, getting a single note, creating notes, and deleting notes. For the tests, we also need a helper class (like `WC_Helper_Order`) to create test notes. The tests also check deleting notes, but nothing has changed in the API here.

To test:

- Run `phpunit`
- Check out a few order note responses, `/wc/v3/orders/{orderId}/notes/`,  `/wc/v3/orders/{orderId}/notes/{noteId}`
- Request the schema (by using `OPTIONS`) to see that `author` and `added_by_user` have been added.
- Create a note by POSTing content, see [these docs for how](http://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order-note), you can also add `added_by_user: true` to set the note author to your authenticated user.

Note: We can hold off release for the composer update, this isn't an urgent issue.

### CODE REVIEW

**Review by mikejolley — APPROVED** [review]
LGTM

**Review by emdashcodes — APPROVED** [review]
Code LGTM.

I tested in Postman and the responses look good. I was able to use the `added_by_user` flag when creating an order note.

There are 4 failing unit tests with this branch, but they are not related to the code here. They are fixed in #47.

The only other thing I wanted to mention here is that functions like `wc_delete_order_note` are new in WooCommerce 3.2. That means you must be running beta/master for these endpoints & tests to work.

I mention this for two reasons:

* Using those functions means we can't launch until after 3.2 final goes live. AT sites will auto-update so they should get the latest magic. That would be October 4th. In terms of Q3 goals/launching that's close, but it would be nice to not be blocked from launching (cc @kellychoffman) .
* If we test these endpoints/pages in Calypso, we need to make sure our test sites are also running 3.2/master.

It might be worth using 3.1 logic for now with TODOs to update later, until we can reliably use those functions for our needs.

**Review by emdashcodes — CHANGES_REQUESTED** [review]
Edit to the above:

Let's go ahead and make these work in 3.1 with TODOs to update later. We don't want to be blocked by 3.2. Sorry for the extra work here. Hopefully it should just be using some wp/wc functions directly, or a shim could work.

**Comment by ryelle** [comment]
This is not used in calypso yet - IMO we can wait for 3.2 to avoid doing the extra work right now (not sure I actually have time to make the calypso PR before the GM anyway). Nothing is actually blocked in calypso, just whether we show the author name in the order notes.

**Comment by emdashcodes** [comment]
@ryelle That's fair 👍. We keep that part out until 3.2 drops.

**Review by emdashcodes — APPROVED** [review]

**Comment by emdashcodes** [comment]
I ran through the testing steps one more time and everything works. There are a couple failing PHPUnit tests but those were fixed in master awhile ago. @ryelle Can you rebase this?

Now that 3.2 is out, I think we could go ahead and get this deployed in the next update along-side the code removal. cc @timmyc.

**Comment by timmyc** [comment]
I have rebased but am getting errors when running `phpunit` - @justinshreve are the tests passing for you?

```
PHP Warning:  require_once(/srv/www/wordpress-develop/public_html/src/wp-content/plugins/woocommerce/tests/framework/factories/class-wc-unit-test-factory-for-webhook.php): failed to open stream: No such file or directory in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/wc-api-dev/tests/bootstrap.php on line 107

Warning: require_once(/srv/www/wordpress-develop/public_html/src/wp-content/plugins/woocommerce/tests/framework/factories/class-wc-unit-test-factory-for-webhook.php): failed to open stream: No such file or directory in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/wc-api-dev/tests/bootstrap.php on line 107
PHP Fatal error:  require_once(): Failed opening required '/srv/www/wordpress-develop/public_html/src/wp-content/plugins/woocommerce/tests/framework/factories/class-wc-unit-test-factory-for-webhook.php' (include_path='.:/usr/share/php') in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/wc-api-dev/tests/bootstrap.php on line 107

Fatal error: require_once(): Failed opening required '/srv/www/wordpress-develop/public_html/src/wp-content/plugins/woocommerce/tests/framework/factories/class-wc-unit-test-factory-for-webhook.php' (include_path='.:/usr/share/php') in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/wc-api-dev/tests/bootstrap.php on line 107
```

**Pull request merged**
