### PR TITLE
Disable jetpack sync during REST requests

### LINKED ISSUE #27: Disable Jetpack Sync during Shutdown for REST API Requests
Jetpack sync during the `shutdown` hook is adding about 4 seconds to product creation and probably other requests too.

Let's filter `jetpack_sync_sender_should_load` to false during a `REST_REQUEST` as a temporary measure, until

* WordPress core has a release that includes a fix for https://core.trac.wordpress.org/ticket/41358#ticket
* Jetpack has a release that includes https://github.com/Automattic/jetpack/pull/7482

See also https://github.com/woocommerce/woocommerce/pull/16158

cc @mikejolley @westi @DanReyLop @justinshreve

### PR DESCRIPTION
**Pull request by allendav**
Fixes #27 

To test:
* Use a tool like Postman to create a product using the REST API
* Note the horribly long creation time (e.g. approx 5 seconds)
* Install this branch
* Create another product
* Note the wonderfully short creation time (e.g. approx 2 seconds)
* Profit!

Note: Bumps version to 0.7.0 also

cc @justinshreve or @DanReyLop for review
cc @westi

### CODE REVIEW

**Review by DanReyLop — APPROVED** [review]
This is night and day. Thanks for a quick fix! :shipit:

**Comment by emdashcodes** [comment]
I don't see any issues with the code. But I'm having some trouble seeing much improvements when testing :(. I'm not sure if I'm doing anything wrong, but I installed the new version, generated some keys, and did a simple POST to products from Postman.

On `justin-devstore-at.blog`, an Atomic site, I'm getting around 5 seconds with 0.6 of the plugin, and the same with 0.7 of the plugin. A few times I got less than 2, but I was able to get that in both cases occasionally. `justin-devstore-at.blog` doesn't have any additional plugins installed except for the ones WordPress.com & the Store setup add.

On `wootest.mystagingwebsite.com` I am getting sub 2 seconds for both versions.

It seems like 0.7 might be slightly faster, but I'm definitely not getting any huge improvements. It could just be me, or something else -- especially if you and others are definitely seeing a difference. Let me know if I can provide any more info.

**Comment by DanReyLop** [comment]
Wait, that's true, it's not working for me either. The last time I tried it I may have gotten lucky, I got a couple of less-than-1-second requests in a row and I assumed it was working.

I've added some logging and `REST_REQUEST` is not defined.

**Review by DanReyLop — CHANGES_REQUESTED** [review]
.

**Comment by emdashcodes** [comment]
I added some debug right before the return:

```
echo 'defined? ' . defined( 'REST_REQUEST' );
echo 'REST_REQUEST ' . REST_REQUEST;
echo 'sender_should_load: ' . $sender_should_load;
```

```
defined? false 
REST_REQUEST REST_REQUEST
sender_should_load: 1
```

**Comment by emdashcodes** [comment]
Posting this from Slack:

from @DanReyLop 

> The `jetpack_sync_sender_should_load` filter is called in `init`, so at that point the `REST_REQUEST` constant isn't defined yet. This is gonna be more hacky than it should

I suggest maybe checking `REQUEST_URI` to see if it contains `/wc/v3`? That is the only idea I have. It's a bit hackier, but should still get the job done.

**Comment by allendav** [comment]
Fixing this now. I only did 3 requests and they all came in at 2 seconds. I'll run the automated tests after fixing it to look at the request uri instead and make sure it is consistently better then

**Review by emdashcodes — APPROVED** [review]
Looks good. And is working consistently for me now. Definitely much much faster.

**Pull request merged**
