### PR TITLE
Remove `/data/counts` and `/products/reviews` endpoints

### LINKED ISSUE #49: Migrate Store-Specific Endpoints
Background: https://github.com/woocommerce/woocommerce/pull/20116

In preparation for `wc/v3` endpoints from `wc-api-dev` being merged into core - there are two endpoints that are not going to be migrated:

- `products/reviews`
- `data/counts`

This issue will need to involve removal of the above endpoint logic from `wc-api-dev`, and moving the same endpoint code to `wc-calypso-bridge`. It sounds like both endpoints, in some form or another may make their way into core eventually, but until then we will need to get the logic for them into this plugin so Store users can still utilize the functionality.

### PR DESCRIPTION
**Pull request by emdashcodes**
Partially fixes https://github.com/Automattic/wc-calypso-bridge/issues/49.

This PR removes the `/data/counts` and `/products/reviews` endpoints from `wc-api-dev`. These endpoints are being moved to `wc-calypso-bridge`. See https://github.com/woocommerce/woocommerce/pull/20116.

The product reviews class needs to stick around, so `/products/$product_id/reviews` still work via v3 paths (which is an existing core endpoint).

This PR also bumps the version number.

To Test:
* See testing directions on https://github.com/Automattic/wc-calypso-bridge/pull/50.

### CODE REVIEW

**Review by timmyc — COMMENTED** [review]
Do we need to remove this line also?

https://github.com/woocommerce/wc-api-dev/blob/master/wc-api-dev-class.php#L69

**Comment by emdashcodes** [comment]
> Do we need to remove this line also?

@timmyc It is removed here https://github.com/woocommerce/wc-api-dev/pull/112/files#diff-a7caecc84e756856a46f9ebc7839a234L69

Or did you mean product reviews? That file needs to stay (to make the core product review endpoints available over v3).

**Comment by timmyc** [comment]
Doh! totally missed that, sorry!

**Review by timmyc — APPROVED** [review]
LGTM!

**Pull request merged**
