### PR TITLE
Don't return parent image for variations.

### PR DESCRIPTION
**Pull request by emdashcodes**
This makes two updates to the previous PR (#1):

* Now that we have `prepare_object_for_response` in this controller, we can drop the nested array/`current` call.
* I introduced an unintended change in #1 -- the parent product image is getting returned if there was no variation image (since `get_image_id` returns it). This fixes the behavior so the parent image is NOT returned if the variation doesn't explicitly have one (just like v1 and v2).

### CODE REVIEW

**Comment by claudiosanches** [comment]
I like this change, just not sure about return an empty array, since the `image` is object in the json, maybe better return `null`.

**Comment by emdashcodes** [comment]
@claudiosanches It does return `null` 😄

**Comment by claudiosanches** [comment]
@justinshreve ohh yeah, sorry xD

**Review by claudiosanches — APPROVED** [review]
LGTM

**Pull request merged**
